// Contains personal details for people by kerberos.

var people = {
  "cheber" : {
    name: "Caitlin",
    full_name: "Caitlin Heber",
    year: "2016",
    room: "733",
    phone: "360-434-0385",
    email: "cheber@mit.edu",
    photo: "cheber.jpg",
  },
  "kmfarris" : {
    name: "Kate",
    full_name: "Kate Farris",
    year: "2017",
    room: "732",
    email: "kmfarris@mit.edu",
    photo: "kmfarris.jpg",
  },
  "jujzwang" : {
    name: "Juju",
    full_name: "Juju Wang",
    year: "2017",
    room: "732",
    email: "jujzwang@mit.edu",
    photo: "jujzwang.jpg",
  },
  "colbertc" : {
    name: "Caroline",
    full_name: "Caroline Colbert",
    year: "2017",
    room: "635",
    email: "colbertc@mit.edu",
    photo: "colbertc.jpg",
  },
  "dafolabi" : {
    name: "David",
    full_name: "David Afolabi",
    year: "2016",
    room: "1021A",
    phone: "765-491-5528",
    email: "dafolabi@mit.edu",
    photo: "dafolabi.jpg",
  },
  "adelmore" : {
    name: "Alex",
    full_name: "Alex Delmore",
    year: "2017",
    room: "1040",
    phone: "508-431-3365",
    email: "adelmore@mit.edu",
    photo: "akurtz-adelmore.jpg",
  },
  "akurtz" : {
    name: "Andrew",
    full_name: "Andrew Kurtz",
    year: "2017",
    room: "727",
    phone: "201-981-0200",
    email: "akurtz@mit.edu",
    photo: "akurtz-adelmore.jpg",
  },
  "magallon" : {
    name: "Nadia",
    full_name: "Nadia Magallon",
    year: "2017",
    room: "1040",
    phone: "703-568-6779",
    email: "magallon@mit.edu",
    photo: "magallon-gschulte.jpg",
  },
  "gschulte" : {
    name: "Garrett",
    full_name: "Garrett Schulte",
    year: "2017",
    room: "1073",
    email: "gschulte@mit.edu",
    photo: "magallon-gschulte.jpg",
  },
  "aliciacm" : {
    name: "Alicia",
    full_name: "Alicia Cabrera-Mino",
    year: "2017",
    room: "866",
    email: "aliciacm@mit.edu",
    photo: "aliciacm.jpg",
  },
    "ambhave" : {
    name: "Amol",
    full_name: "Amol Bhave",
    year: "2017",
    room: "724",
    email: "ambhave@mit.edu",
    photo: "ambhave.jpg",
  },
  "amohr" : {
    name: "Alan",
    full_name: "Alan Mohr",
    year: "2017",
    room: "821",
    email: "amohr@mit.edu",
    photo: "amohr.jpg",
  },
    "aoriole" : {
    name: "Alexis",
    full_name: "Alexis Oriole",
    year: "2018",
    room: "552",
    email: "aoriole@mit.edu",
    photo: "aoriole.jpg",
  },
    "chauhans" : {
    name: "Shivani",
    full_name: "Shivani Chauhan",
    year: "2018",
    room: "1022B",
    email: "chauhans@mit.edu",
    photo: "chauhans-snvd.jpg",
  },
    "snvd" : {
    name: "Sarah",
    full_name: "Sarah Van Dierdonck",
    year: "2018",
    room: "472",
    email: "snvd@mit.edu",
    photo: "snvd.jpg",
  },
    "cstubbe" : {
    name: "Camille",
    full_name: "Camille Stubbe",
    year: "2018",
    room: "833",
    email: "cstubbe@mit.edu",
    photo: "cstubbe.jpg",
  },
    "edenmark" : {
    name: "Evan",
    full_name: "Evan Denmark",
    year: "2017",
    room: "1039",
    email: "edenmark@mit.edu",
    photo: "edenmark-irena_m.jpg",
  },
    "kkim17" : {
    name: "Kristina",
    full_name: "Kristina Kim",
    year: "2017",
    room: "846",
    email: "kkim17@mit.edu",
    photo: "kkim17.jpg",
  },
    "loctrinh" : {
    name: "Loc",
    full_name: "Loc Trinh",
    year: "2018",
    room: "340A",
    email: "loctrinh@mit.edu",
    photo: "loctrinh-evancb.jpg",
  },
    "evancb" : {
    name: "Evan",
    full_name: "Evan Brown",
    year: "2018",
    room: "933",
    email: "evancb@mit.edu",
    photo: "loctrinh-evancb.jpg",
  },
    "mecunha" : {
    name: "Elaine",
    full_name: "(Mary) Elaine Cunha",
    year: "2017",
    room: "866",
    email: "mecunha@mit.edu",
    photo: "mecunha.jpg",
  },
    "rgulland" : {
    name: "Ryan",
    full_name: "Ryan Gulland",
    year: "2018",
    room: "340A",
    email: "rgulland@mit.edu",
    photo: "rgulland.jpg",
  },
    "yji" : {
    name: "Yuge",
    full_name: "Yuge Ji",
    year: "2018",
    room: "540",
    email: "yji@mit.edu",
    photo: "yji.jpg",
  },

  // HOUSE TEAM
  "jessig" : {
    name: "John",
    full_name: "John Essigmann",
    year: "1970",
    room: "265",
    email: "jessig@mit.edu",
    photo: "emessig.jpg",
  },
  "emessig" : {
    name: "Ellen",
    full_name: "Ellen Essigmann",
    room: "265",
    email: "emessig@mit.edu",
    photo: "emessig.jpg",
  },
  "srhall" : {
    name: "Steve",
    full_name: "Steve Hall",
    year: "1980",
    room: "772",
    email: "srhall@mit.edu",
    photo: "srhall.jpg",
  },
  "jogon_1" : {
    name: "Josh",
    full_name: "Josh Gonzalez",
    room: "580",
    email: "jogon_1@mit.edu",
    photo: "jogon_1.jpg",
  },

  // OTHER
  "nika_h" : {
    name: "Nika",
    full_name: "Nika Hollingsworth",
    room: "N/A",
    email: "nika_h@mit.edu",
    photo: "nika_h.jpg",
  },
  "vacant" : {
    name: "-",
    full_name: "Vacant",
    photo: "photo.jpg",
  },

}