// Contains personal details for people by kerberos.

var people = {
  "yji" : {
    name: "Yuge",
    full_name: "Yuge Ji",
    year: "2018",
    room: "540",
    email: "yji@mit.edu",
    photo: "yji.jpg",
  },
  "jujzwang" : {
    name: "Juju",
    full_name: "(Zhishen) Juju Wang",
    year: "2017",
    room: "732",
    email: "jujzwang@mit.edu",
    photo: "jujzwang.jpg",
  },
  "solveig3" : {
    name: "Tinna",
    full_name: "Tinna-Solveig Kosoko-Thoroddsen",
    year: "2019",
    room: "522B",
    email: "solveig3@mit.edu",
    photo: "tinna.jpg",
  },
  "amohr" : {
    name: "Alan",
    full_name: "Alan Mohr",
    year: "2017",
    room: "821",
    email: "amohr@mit.edu",
    photo: "amohr.jpg",
  },
  "lilydove" : {
    name: "Lily",
    full_name: "Lilian Dove",
    year: "2018",
    room: "337",
    email: "lilydove@mit.edu",
    photo: "lily.jpg",
  },
  "cramjee" : {
    name: "Christine",
    full_name: "Christine Ramjee",
    year: "2019",
    room: "379B",
    email: "cramjee@mit.edu",
    photo: "christine.jpg",
  },
  "ambhave" : {
    name: "Amol",
    full_name: "Amol Bhave",
    year: "2017",
    room: "724",
    email: "ambhave@mit.edu",
    photo: "amol-loc.jpg",
  },
  "loctrinh" : {
    name: "Loc",
    full_name: "Loc Trinh",
    year: "2018",
    room: "340A",
    email: "loctrinh@mit.edu",
    photo: "loctrinh-evancb.jpg",
  },
  "khn" : {
    name: "Khanh",
    full_name: "Khanh Nguyen",
    year: "2019",
    room: "340B",
    email: "khn@mit.edu",
    photo: "khanh-john.jpg",
  },
  "johnsili" : {
    name: "John",
    full_name: "Shi Jie Li",
    year: "2019",
    room: "378",
    email: "johnsili@mit.edu",
    photo: "photo.jpg",
  },
  "aoriole" : {
    name: "Alexis",
    full_name: "Alexis Oriole",
    year: "2018",
    room: "552",
    email: "aoriole@mit.edu",
    photo: "aoriole.jpg",
  },
  "pliscio" : {
    name: "Patrick",
    full_name: "Patrick Liscio",
    year: "2017",
    room: "721",
    email: "pliscio@mit.edu",
    photo: "pliscio.jpg",
  },
  "cstubbe" : {
    name: "Camille",
    full_name: "Camille Stubbe",
    year: "2018",
    room: "833",
    email: "cstubbe@mit.edu",
    photo: "cstubbe.jpg",
  },
  "mfeffer" : {
    name: "Michael",
    full_name: "Michael Feffer",
    year: "2018",
    room: "377",
    email: "mfeffer@mit.edu",
    photo: "photo.jpg",
  },
  "evancb" : {
    name: "Evan",
    full_name: "Evan Brown",
    year: "2018",
    room: "933",
    email: "evancb@mit.edu",
    photo: "photo.jpg",
  },
  "sharc" : {
    name: "Sharlene",
    full_name: "Sharlene Chiu",
    year: "2019",
    room: "525",
    email: "sharc@mit.edu",
    photo: "evan-sharlene.jpg",
  },
  "walaa" : {
    name: "Walaa",
    full_name: "Walaa Alkhanaizi",
    year: "2019",
    room: "522c",
    email: "walaa@mit.edu",
    photo: "photo.jpg",
  },
  "merealoy" : {
    name: "Meredith",
    full_name: "Meredith Loy",
    year: "2019",
    room: "924",
    email: "merealoy@mit.edu",
    photo: "photo.jpg",
  },
  "marquezm" : {
    name: "Matthew",
    full_name: "Matthew Marquez",
    year: "2019",
    room: "225",
    email: "marquezm@mit.edu",
    photo: "matthew.jpg",
  },
  "sayala" : {
    name: "Sofia",
    full_name: "Sofia Ayala",
    year: "2019",
    room: "379A",
    email: "sayala@mit.edu",
    photo: "photo.jpg",
  },
  "aqcao" : {
    name: "Amanda",
    full_name: "Amanda Cao",
    year: "2019",
    room: "379A",
    email: "aqcao@mit.edu",
    photo: "amanda.jpg",
  },
  "jhbell" : {
    name: "John",
    full_name: "John Bell",
    year: "2018",
    room: "380",
    email: "jhbell@mit.edu",
    photo: "photo.jpg",
  },
  "daynae" : {
    name: "Dayna",
    full_name: "Dayna Erdmann",
    year: "2019",
    room: "224A",
    email: "daynae@mit.edu",
    photo: "dayna.jpg",
  },
  "jacqliu" : {
    name: "Jacqueline",
    full_name: "Jacqueline Liu",
    year: "2018",
    room: "337",
    email: "jacqliu@mit.edu",
    photo: "jacqui.jpg",
  },
  "amowayed" : {
    name: "Mohsen",
    full_name: "Abdulmohsen Alowayed",
    year: "2018",
    room: "381",
    email: "amowayed@mit.edu",
    photo: "mohsen.jpg",
  },
  "mecunha" : {
    name: "Elaine",
    full_name: "(Mary) Elaine Cunha",
    year: "2017",
    room: "866",
    email: "mecunha@mit.edu",
    photo: "mecunha.jpg",
  },
  "rgulland" : {
    name: "Ryan",
    full_name: "Ryan Gulland",
    year: "2018",
    room: "340A",
    email: "rgulland@mit.edu",
    photo: "rgulland.jpg",
  },

  "kianna" : {
    name: "Kianna",
    full_name: "Kianna Jackson",
    year: "2016",
    room: "577",
    email: "kianna@mit.edu",
    photo: "photo.jpg",
  },

  // HOUSE TEAM
  "jessig" : {
    name: "John",
    full_name: "John Essigmann",
    year: "1970",
    room: "265",
    email: "jessig@mit.edu",
    photo: "emessig.jpg",
  },
  "emessig" : {
    name: "Ellen",
    full_name: "Ellen Essigmann",
    room: "265",
    email: "emessig@mit.edu",
    photo: "emessig.jpg",
  },
  "srhall" : {
    name: "Steve",
    full_name: "Steve Hall",
    year: "1980",
    room: "772",
    email: "srhall@mit.edu",
    photo: "srhall.jpg",
  },
  "jogon_1" : {
    name: "Josh",
    full_name: "Josh Gonzalez",
    room: "580",
    email: "jogon_1@mit.edu",
    photo: "jogon_1.jpg",
  },

  // OTHER
  "nika_h" : {
    name: "Nika",
    full_name: "Nika Hollingsworth",
    room: "N/A",
    email: "nika_h@mit.edu",
    photo: "nika_h.jpg",
  },
  "vacant" : {
    name: "-",
    full_name: "Vacant",
    photo: "photo.jpg",
  },

}