// Contains personal details for people by kerberos.

var people = {
  "larsj" : {
    name: "Lars",
    full_name: "Lars Johnson",
    year: "2015",
    room: "667",
    phone: "615-319-3487",
    email: "larsj@mit.edu",
    photo: "larsj.jpg",
    facebook: "https://www.facebook.com/lrsjohnson",
  },
  "cheber" : {
    name: "Caitlin",
    full_name: "Caitlin Heber",
    year: "2016",
    room: "733",
    phone: "360-434-0385",
    email: "cheber@mit.edu",
    photo: "cheber.jpg",
    facebook: "https://www.facebook.com/caitlin.heber",
  },
  "kmfarris" : {
    name: "Kate",
    full_name: "Kate Farris",
    year: "2017",
    room: "371",
    email: "kmfarris@mit.edu",
    photo: "kmfarris.jpg",
    facebook: "https://www.facebook.com/kate.farris.5",
  },
  "woursler" : {
    name: "Will",
    full_name: "Will Oursler",
    year: "2015",
    room: "631D",
    phone: "617-123-4567",
    email: "wourlser@mit.edu",
    photo: "woursler.jpg",
  },

  "orlowski" : {
    name: "Jesse",
    full_name: "Jesse Orlowski",
    year: "2016",
    room: "966",
    email: "orlowski@mit.edu",
    photo: "orlowski.jpg",
    facebook: "https://www.facebook.com/jesse.orlowski24",
  },
  "jujzwang" : {
    name: "Juju",
    full_name: "Juju Wang",
    year: "2017",
    room: "371",
    email: "jujzwang@mit.edu",
    photo: "jujzwang.jpg",
    facebook: "https://www.facebook.com/JujuMegalopolis",
  },
  "colbertc" : {
    name: "Caroline",
    full_name: "Caroline Colbert",
    year: "2017",
    room: "939",
    email: "colbertc@mit.edu",
    photo: "colbertc.jpg",
    facebook: "https://www.facebook.com/caroline.colbert.7",
  },
  "adat" : {
    name: "Ada",
    full_name: "Ada Taylor",
    year: "2016",
    room: "674",
    email: "adat@mit.edu",
    photo: "adat.jpg",
    facebook: "https://www.facebook.com/ada",
  },

  "cfh119" : {
    name: "Christian",
    full_name: "Christian",
    year: "2015",
    room: "1072",
    email: "cfh119@mit.edu",
    photo: "cfh119.jpg",
    facebook: "https://www.facebook.com/christian.hyacinthe.9",
  },
  "apark93" : {
    name: "Allen",
    full_name: "Allen Park",
    year: "2015",
    room: "578A",
    phone: "404-775-3661",
    email: "apark93@mit.edu",
    photo: "apark93.jpg",
    facebook: "https://www.facebook.com/alan.kim1",
  },
  "nhynes" : {
    name: "Nick",
    full_name: "Nick Hynes",
    year: "2016",
    room: "673",
    email: "nhynes@mit.edu",
    photo: "nhynes.jpg",
  },
  "cosmosd" : {
    name: "Cosmos",
    full_name: "Cosmos Darwin",
    year: "2015",
    room: "678",
    phone: "617-412-0949",
    email: "cosmosd@mit.edu",
    photo: "cosmosd.jpg",
    facebook: "https://www.facebook.com/cosmosdarwin",
  },
  "dafolabi" : {
    name: "David",
    full_name: "David Afolabi",
    year: "2016",
    room: "426",
    phone: "765-491-5528",
    email: "dafolabi@mit.edu",
    photo: "dafolabi.jpg",
    facebook: "https://www.facebook.com/dav.afolabi",
  },

  "erdozain" : {
    name: "Jack",
    full_name: "Jack Erdozain",
    year: "2016",
    room: "572A",
    email: "erdozain@mit.edu",
    photo: "erdozain.jpg",
    facebook: "https://www.facebook.com/jack.erdozain",
  },
  "adelmore" : {
    name: "Alex",
    full_name: "Alex Delmore",
    year: "2017",
    room: "721",
    phone: "508-431-3365",
    email: "adelmore@mit.edu",
    photo: "akurtz.jpg",
    facebook: "https://www.facebook.com/alex.delmore",
  },
  "akurtz" : {
    name: "Andrew",
    full_name: "Andrew Kurtz",
    year: "2017",
    room: "373",
    phone: "201-981-0200",
    email: "akurtz@mit.edu",
    photo: "akurtz.jpg",
    facebook: "https://www.facebook.com/kurtzinater",
  },
  "cwetters" : {
    name: "Christina",
    full_name: "Christina Wettersten",
    year: "2015",
    room: "1021C",
    email: "cwetters@mit.edu",
    photo: "cwetters.jpg",
    facebook: "https://www.facebook.com/christina.wettersten",
  },
  "magallon" : {
    name: "Nadia",
    full_name: "Nadia Magallon",
    year: "2017",
    room: "721",
    phone: "703-568-6779",
    email: "magallon@mit.edu",
    photo: "magallon.jpg",
    facebook: "https://www.facebook.com/nadia.magallon.9",
  },
  "gschulte" : {
    name: "Garrett",
    full_name: "Garrett Schulte",
    year: "2017",
    room: "741A",
    email: "gschulte@mit.edu",
    photo: "gschulte.jpg",
    facebook: "https://www.facebook.com/garrett.schulte.33",
  },
  "kaugdahl" : {
    name: "Kirsten",
    full_name: "Kirsten Augdahl",
    year: "2016",
    room: "664",
    email: "kaugdahl@mit.edu",
    photo: "kaugdahl.jpg",
    facebook: "https://www.facebook.com/kirsten.augdahl",
  },

  // HOUSE TEAM
  "jessig" : {
    name: "John",
    full_name: "John Essigmann",
    year: "1970",
    room: "265",
    email: "jessig@mit.edu",
    photo: "emessig.jpg",
  },
  "emessig" : {
    name: "Ellen",
    full_name: "Ellen Essigmann",
    room: "265",
    email: "emessig@mit.edu",
    photo: "emessig.jpg",
  },
  "srhall" : {
    name: "Steve",
    full_name: "Steve Hall",
    year: "1980",
    room: "772",
    email: "srhall@mit.edu",
    photo: "srhall.jpg",
  },
  "jogon_1" : {
    name: "Josh",
    full_name: "Josh Gonzalez",
    room: "580",
    email: "jogon_1@mit.edu",
    photo: "jogon_1.jpg",
  },

  // OTHER
  "nika_h" : {
    name: "Nika",
    full_name: "Nika Hollingsworth",
    room: "N/A",
    email: "nika_h@mit.edu",
    photo: "nika_h.jpg",
  },
  "vacant" : {
    name: "-",
    full_name: "Vacant",
    photo: "photo.jpg",
  },

}